/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ManifestDotwebmanifestRouteImport } from './routes/manifest[.]webmanifest'
import { Route as NameRouteImport } from './routes/$name'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiVapidPublicKeyRouteImport } from './routes/api/vapid-public-key'
import { Route as ApiLoginRouteImport } from './routes/api/login'
import { Route as ApiClaimRouteImport } from './routes/api/claim'
import { Route as ConnectNameIndexRouteImport } from './routes/connect/$name/index'
import { Route as ConnectNameManifestDotwebmanifestRouteImport } from './routes/connect/$name/manifest[.]webmanifest'
import { Route as ApiNotifyNameRouteImport } from './routes/api/notify/$name'
import { Route as ApiChannelNameRouteImport } from './routes/api/channel/$name'
import { Route as ApiChannelNameSubscribeRouteImport } from './routes/api/channel/$name/subscribe'
import { Route as ApiChannelNameNotificationsRouteImport } from './routes/api/channel/$name/notifications'
import { Route as ApiChannelNameEnsureRouteImport } from './routes/api/channel/$name/ensure'

const ManifestDotwebmanifestRoute = ManifestDotwebmanifestRouteImport.update({
  id: '/manifest.webmanifest',
  path: '/manifest.webmanifest',
  getParentRoute: () => rootRouteImport,
} as any)
const NameRoute = NameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVapidPublicKeyRoute = ApiVapidPublicKeyRouteImport.update({
  id: '/api/vapid-public-key',
  path: '/api/vapid-public-key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLoginRoute = ApiLoginRouteImport.update({
  id: '/api/login',
  path: '/api/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClaimRoute = ApiClaimRouteImport.update({
  id: '/api/claim',
  path: '/api/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectNameIndexRoute = ConnectNameIndexRouteImport.update({
  id: '/connect/$name/',
  path: '/connect/$name/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectNameManifestDotwebmanifestRoute =
  ConnectNameManifestDotwebmanifestRouteImport.update({
    id: '/connect/$name/manifest.webmanifest',
    path: '/connect/$name/manifest.webmanifest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiNotifyNameRoute = ApiNotifyNameRouteImport.update({
  id: '/api/notify/$name',
  path: '/api/notify/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChannelNameRoute = ApiChannelNameRouteImport.update({
  id: '/api/channel/$name',
  path: '/api/channel/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChannelNameSubscribeRoute = ApiChannelNameSubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => ApiChannelNameRoute,
} as any)
const ApiChannelNameNotificationsRoute =
  ApiChannelNameNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => ApiChannelNameRoute,
  } as any)
const ApiChannelNameEnsureRoute = ApiChannelNameEnsureRouteImport.update({
  id: '/ensure',
  path: '/ensure',
  getParentRoute: () => ApiChannelNameRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$name': typeof NameRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/api/claim': typeof ApiClaimRoute
  '/api/login': typeof ApiLoginRoute
  '/api/vapid-public-key': typeof ApiVapidPublicKeyRoute
  '/api/channel/$name': typeof ApiChannelNameRouteWithChildren
  '/api/notify/$name': typeof ApiNotifyNameRoute
  '/connect/$name/manifest.webmanifest': typeof ConnectNameManifestDotwebmanifestRoute
  '/connect/$name/': typeof ConnectNameIndexRoute
  '/api/channel/$name/ensure': typeof ApiChannelNameEnsureRoute
  '/api/channel/$name/notifications': typeof ApiChannelNameNotificationsRoute
  '/api/channel/$name/subscribe': typeof ApiChannelNameSubscribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$name': typeof NameRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/api/claim': typeof ApiClaimRoute
  '/api/login': typeof ApiLoginRoute
  '/api/vapid-public-key': typeof ApiVapidPublicKeyRoute
  '/api/channel/$name': typeof ApiChannelNameRouteWithChildren
  '/api/notify/$name': typeof ApiNotifyNameRoute
  '/connect/$name/manifest.webmanifest': typeof ConnectNameManifestDotwebmanifestRoute
  '/connect/$name': typeof ConnectNameIndexRoute
  '/api/channel/$name/ensure': typeof ApiChannelNameEnsureRoute
  '/api/channel/$name/notifications': typeof ApiChannelNameNotificationsRoute
  '/api/channel/$name/subscribe': typeof ApiChannelNameSubscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$name': typeof NameRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/api/claim': typeof ApiClaimRoute
  '/api/login': typeof ApiLoginRoute
  '/api/vapid-public-key': typeof ApiVapidPublicKeyRoute
  '/api/channel/$name': typeof ApiChannelNameRouteWithChildren
  '/api/notify/$name': typeof ApiNotifyNameRoute
  '/connect/$name/manifest.webmanifest': typeof ConnectNameManifestDotwebmanifestRoute
  '/connect/$name/': typeof ConnectNameIndexRoute
  '/api/channel/$name/ensure': typeof ApiChannelNameEnsureRoute
  '/api/channel/$name/notifications': typeof ApiChannelNameNotificationsRoute
  '/api/channel/$name/subscribe': typeof ApiChannelNameSubscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$name'
    | '/manifest.webmanifest'
    | '/api/claim'
    | '/api/login'
    | '/api/vapid-public-key'
    | '/api/channel/$name'
    | '/api/notify/$name'
    | '/connect/$name/manifest.webmanifest'
    | '/connect/$name/'
    | '/api/channel/$name/ensure'
    | '/api/channel/$name/notifications'
    | '/api/channel/$name/subscribe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$name'
    | '/manifest.webmanifest'
    | '/api/claim'
    | '/api/login'
    | '/api/vapid-public-key'
    | '/api/channel/$name'
    | '/api/notify/$name'
    | '/connect/$name/manifest.webmanifest'
    | '/connect/$name'
    | '/api/channel/$name/ensure'
    | '/api/channel/$name/notifications'
    | '/api/channel/$name/subscribe'
  id:
    | '__root__'
    | '/'
    | '/$name'
    | '/manifest.webmanifest'
    | '/api/claim'
    | '/api/login'
    | '/api/vapid-public-key'
    | '/api/channel/$name'
    | '/api/notify/$name'
    | '/connect/$name/manifest.webmanifest'
    | '/connect/$name/'
    | '/api/channel/$name/ensure'
    | '/api/channel/$name/notifications'
    | '/api/channel/$name/subscribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NameRoute: typeof NameRoute
  ManifestDotwebmanifestRoute: typeof ManifestDotwebmanifestRoute
  ApiClaimRoute: typeof ApiClaimRoute
  ApiLoginRoute: typeof ApiLoginRoute
  ApiVapidPublicKeyRoute: typeof ApiVapidPublicKeyRoute
  ApiChannelNameRoute: typeof ApiChannelNameRouteWithChildren
  ApiNotifyNameRoute: typeof ApiNotifyNameRoute
  ConnectNameManifestDotwebmanifestRoute: typeof ConnectNameManifestDotwebmanifestRoute
  ConnectNameIndexRoute: typeof ConnectNameIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/manifest.webmanifest': {
      id: '/manifest.webmanifest'
      path: '/manifest.webmanifest'
      fullPath: '/manifest.webmanifest'
      preLoaderRoute: typeof ManifestDotwebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$name': {
      id: '/$name'
      path: '/$name'
      fullPath: '/$name'
      preLoaderRoute: typeof NameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vapid-public-key': {
      id: '/api/vapid-public-key'
      path: '/api/vapid-public-key'
      fullPath: '/api/vapid-public-key'
      preLoaderRoute: typeof ApiVapidPublicKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/login': {
      id: '/api/login'
      path: '/api/login'
      fullPath: '/api/login'
      preLoaderRoute: typeof ApiLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/claim': {
      id: '/api/claim'
      path: '/api/claim'
      fullPath: '/api/claim'
      preLoaderRoute: typeof ApiClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect/$name/': {
      id: '/connect/$name/'
      path: '/connect/$name'
      fullPath: '/connect/$name/'
      preLoaderRoute: typeof ConnectNameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect/$name/manifest.webmanifest': {
      id: '/connect/$name/manifest.webmanifest'
      path: '/connect/$name/manifest.webmanifest'
      fullPath: '/connect/$name/manifest.webmanifest'
      preLoaderRoute: typeof ConnectNameManifestDotwebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notify/$name': {
      id: '/api/notify/$name'
      path: '/api/notify/$name'
      fullPath: '/api/notify/$name'
      preLoaderRoute: typeof ApiNotifyNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/channel/$name': {
      id: '/api/channel/$name'
      path: '/api/channel/$name'
      fullPath: '/api/channel/$name'
      preLoaderRoute: typeof ApiChannelNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/channel/$name/subscribe': {
      id: '/api/channel/$name/subscribe'
      path: '/subscribe'
      fullPath: '/api/channel/$name/subscribe'
      preLoaderRoute: typeof ApiChannelNameSubscribeRouteImport
      parentRoute: typeof ApiChannelNameRoute
    }
    '/api/channel/$name/notifications': {
      id: '/api/channel/$name/notifications'
      path: '/notifications'
      fullPath: '/api/channel/$name/notifications'
      preLoaderRoute: typeof ApiChannelNameNotificationsRouteImport
      parentRoute: typeof ApiChannelNameRoute
    }
    '/api/channel/$name/ensure': {
      id: '/api/channel/$name/ensure'
      path: '/ensure'
      fullPath: '/api/channel/$name/ensure'
      preLoaderRoute: typeof ApiChannelNameEnsureRouteImport
      parentRoute: typeof ApiChannelNameRoute
    }
  }
}

interface ApiChannelNameRouteChildren {
  ApiChannelNameEnsureRoute: typeof ApiChannelNameEnsureRoute
  ApiChannelNameNotificationsRoute: typeof ApiChannelNameNotificationsRoute
  ApiChannelNameSubscribeRoute: typeof ApiChannelNameSubscribeRoute
}

const ApiChannelNameRouteChildren: ApiChannelNameRouteChildren = {
  ApiChannelNameEnsureRoute: ApiChannelNameEnsureRoute,
  ApiChannelNameNotificationsRoute: ApiChannelNameNotificationsRoute,
  ApiChannelNameSubscribeRoute: ApiChannelNameSubscribeRoute,
}

const ApiChannelNameRouteWithChildren = ApiChannelNameRoute._addFileChildren(
  ApiChannelNameRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NameRoute: NameRoute,
  ManifestDotwebmanifestRoute: ManifestDotwebmanifestRoute,
  ApiClaimRoute: ApiClaimRoute,
  ApiLoginRoute: ApiLoginRoute,
  ApiVapidPublicKeyRoute: ApiVapidPublicKeyRoute,
  ApiChannelNameRoute: ApiChannelNameRouteWithChildren,
  ApiNotifyNameRoute: ApiNotifyNameRoute,
  ConnectNameManifestDotwebmanifestRoute:
    ConnectNameManifestDotwebmanifestRoute,
  ConnectNameIndexRoute: ConnectNameIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
