/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ManifestDotwebmanifestRouteImport } from './routes/manifest[.]webmanifest'
import { Route as NameRouteImport } from './routes/$name'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConnectNameRouteImport } from './routes/connect/$name'
import { Route as ApiVapidPublicKeyRouteImport } from './routes/api/vapid-public-key'
import { Route as ApiClaimRouteImport } from './routes/api/claim'
import { Route as ApiNotifyNameRouteImport } from './routes/api/notify/$name'
import { Route as ApiChannelNameRouteImport } from './routes/api/channel/$name'
import { Route as ApiChannelNameSubscribeRouteImport } from './routes/api/channel/$name/subscribe'

const ManifestDotwebmanifestRoute = ManifestDotwebmanifestRouteImport.update({
  id: '/manifest.webmanifest',
  path: '/manifest.webmanifest',
  getParentRoute: () => rootRouteImport,
} as any)
const NameRoute = NameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectNameRoute = ConnectNameRouteImport.update({
  id: '/connect/$name',
  path: '/connect/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVapidPublicKeyRoute = ApiVapidPublicKeyRouteImport.update({
  id: '/api/vapid-public-key',
  path: '/api/vapid-public-key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClaimRoute = ApiClaimRouteImport.update({
  id: '/api/claim',
  path: '/api/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotifyNameRoute = ApiNotifyNameRouteImport.update({
  id: '/api/notify/$name',
  path: '/api/notify/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChannelNameRoute = ApiChannelNameRouteImport.update({
  id: '/api/channel/$name',
  path: '/api/channel/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChannelNameSubscribeRoute = ApiChannelNameSubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => ApiChannelNameRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$name': typeof NameRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/api/claim': typeof ApiClaimRoute
  '/api/vapid-public-key': typeof ApiVapidPublicKeyRoute
  '/connect/$name': typeof ConnectNameRoute
  '/api/channel/$name': typeof ApiChannelNameRouteWithChildren
  '/api/notify/$name': typeof ApiNotifyNameRoute
  '/api/channel/$name/subscribe': typeof ApiChannelNameSubscribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$name': typeof NameRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/api/claim': typeof ApiClaimRoute
  '/api/vapid-public-key': typeof ApiVapidPublicKeyRoute
  '/connect/$name': typeof ConnectNameRoute
  '/api/channel/$name': typeof ApiChannelNameRouteWithChildren
  '/api/notify/$name': typeof ApiNotifyNameRoute
  '/api/channel/$name/subscribe': typeof ApiChannelNameSubscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$name': typeof NameRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/api/claim': typeof ApiClaimRoute
  '/api/vapid-public-key': typeof ApiVapidPublicKeyRoute
  '/connect/$name': typeof ConnectNameRoute
  '/api/channel/$name': typeof ApiChannelNameRouteWithChildren
  '/api/notify/$name': typeof ApiNotifyNameRoute
  '/api/channel/$name/subscribe': typeof ApiChannelNameSubscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$name'
    | '/manifest.webmanifest'
    | '/api/claim'
    | '/api/vapid-public-key'
    | '/connect/$name'
    | '/api/channel/$name'
    | '/api/notify/$name'
    | '/api/channel/$name/subscribe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$name'
    | '/manifest.webmanifest'
    | '/api/claim'
    | '/api/vapid-public-key'
    | '/connect/$name'
    | '/api/channel/$name'
    | '/api/notify/$name'
    | '/api/channel/$name/subscribe'
  id:
    | '__root__'
    | '/'
    | '/$name'
    | '/manifest.webmanifest'
    | '/api/claim'
    | '/api/vapid-public-key'
    | '/connect/$name'
    | '/api/channel/$name'
    | '/api/notify/$name'
    | '/api/channel/$name/subscribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NameRoute: typeof NameRoute
  ManifestDotwebmanifestRoute: typeof ManifestDotwebmanifestRoute
  ApiClaimRoute: typeof ApiClaimRoute
  ApiVapidPublicKeyRoute: typeof ApiVapidPublicKeyRoute
  ConnectNameRoute: typeof ConnectNameRoute
  ApiChannelNameRoute: typeof ApiChannelNameRouteWithChildren
  ApiNotifyNameRoute: typeof ApiNotifyNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/manifest.webmanifest': {
      id: '/manifest.webmanifest'
      path: '/manifest.webmanifest'
      fullPath: '/manifest.webmanifest'
      preLoaderRoute: typeof ManifestDotwebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$name': {
      id: '/$name'
      path: '/$name'
      fullPath: '/$name'
      preLoaderRoute: typeof NameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect/$name': {
      id: '/connect/$name'
      path: '/connect/$name'
      fullPath: '/connect/$name'
      preLoaderRoute: typeof ConnectNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vapid-public-key': {
      id: '/api/vapid-public-key'
      path: '/api/vapid-public-key'
      fullPath: '/api/vapid-public-key'
      preLoaderRoute: typeof ApiVapidPublicKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/claim': {
      id: '/api/claim'
      path: '/api/claim'
      fullPath: '/api/claim'
      preLoaderRoute: typeof ApiClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notify/$name': {
      id: '/api/notify/$name'
      path: '/api/notify/$name'
      fullPath: '/api/notify/$name'
      preLoaderRoute: typeof ApiNotifyNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/channel/$name': {
      id: '/api/channel/$name'
      path: '/api/channel/$name'
      fullPath: '/api/channel/$name'
      preLoaderRoute: typeof ApiChannelNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/channel/$name/subscribe': {
      id: '/api/channel/$name/subscribe'
      path: '/subscribe'
      fullPath: '/api/channel/$name/subscribe'
      preLoaderRoute: typeof ApiChannelNameSubscribeRouteImport
      parentRoute: typeof ApiChannelNameRoute
    }
  }
}

interface ApiChannelNameRouteChildren {
  ApiChannelNameSubscribeRoute: typeof ApiChannelNameSubscribeRoute
}

const ApiChannelNameRouteChildren: ApiChannelNameRouteChildren = {
  ApiChannelNameSubscribeRoute: ApiChannelNameSubscribeRoute,
}

const ApiChannelNameRouteWithChildren = ApiChannelNameRoute._addFileChildren(
  ApiChannelNameRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NameRoute: NameRoute,
  ManifestDotwebmanifestRoute: ManifestDotwebmanifestRoute,
  ApiClaimRoute: ApiClaimRoute,
  ApiVapidPublicKeyRoute: ApiVapidPublicKeyRoute,
  ConnectNameRoute: ConnectNameRoute,
  ApiChannelNameRoute: ApiChannelNameRouteWithChildren,
  ApiNotifyNameRoute: ApiNotifyNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
